## Creating ANN from Scratch. 

In [18]:
import numpy as np


class Perceptron : 
    def __init__(self,num_inputs, learning_rate = 0.1):
        # initalize weights with samell random value
        self.weights = np.random.randn(num_inputs)
        self.bias = np.random.randn()
        self.learning_rate = learning_rate
    
    def activate(self, x):
        # Apply step fun. to weigheted sum
        _result = 0
        if x>=0 : 
            _result=1
            return _result
        else :
            return _result
    
    def predict(self, inputs):
        # Compute weighted sum of inputs 
        weighted_sum = np.dot(inputs,self.weights) + self.bias
        # Apply acivation function. 
        return self.activate(weighted_sum)
    
    def train(self, training_inputs, labels, num_epochs):
        for epoch in range(num_epochs):
            for inputs, label in zip(training_inputs, labels):
                prediction = self.predict(inputs)
                error = label - prediction

                # update weights and bias 
                self.weights += self.learning_rate * error * inputs 
                self.bias += self.learning_rate * error 

        


In [20]:
# Example usage
training_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
labels = np.array([0, 0, 0, 1])

# Create a perceptron with 2 inputs
perceptron = Perceptron(num_inputs=2)

# Train the perceptron. 
perceptron.train(training_inputs, labels, num_epochs=10)

# Test the percpetron 

test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for inputs in test_inputs:
    prediction = perceptron.predict(inputs)
    print(f"Input: {inputs}, Prediction: {prediction}")

Input: [0 0], Prediction: 0
Input: [0 1], Prediction: 0
Input: [1 0], Prediction: 0
Input: [1 1], Prediction: 1


In [9]:
num_inputs = 2

## Dot product for matrix multiplication. 
'''Ann.ipynb
Bais term w0+ w1*x1 + w2*x2

'''
training_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
display(training_inputs.shape)
weights = np.random.randn(num_inputs)
display(weights.shape)
display(weights)

(4, 2)

(2,)

array([0.74479293, 0.32636428])

In [17]:
inputs = [0.5, 0.8, 1.2]
weights = [0.3, 0.4, 0.6]
bias = 0.1

result = np.dot(inputs,weights)  + bias   
print(result)

1.29


does np.dot() automatically take care of matrix transpose ? how is the matrix multiplication impletemented in np.dot() ? give the algorithm and example code with numerical example. 

Yes, `np.dot()` function in NumPy automatically handles the matrix transpose when performing matrix multiplication. The algorithm for matrix multiplication implemented in `np.dot()` follows the standard matrix multiplication algorithm, known as the dot product.

Algorithm for Matrix Multiplication:
1. Given two matrices `A` and `B` with appropriate dimensions, the resulting matrix `C` has dimensions `(m x p) = (m x n) * (n x p)`.
2. Initialize an empty matrix `C` of shape `(m x p)` to store the result.
3. For each element `C[i][j]` in matrix `C`:
   - Compute the dot product of the `i`th row of matrix `A` and the `j`th column of matrix `B`.
   - Sum the element-wise products of corresponding elements from the row of `A` and the column of `B` to obtain the dot product.
   - Assign the dot product to the element `C[i][j]`.

Here's an example code demonstrating matrix multiplication using `np.dot()` with a numerical example:

```python
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Perform matrix multiplication using np.dot()
C = np.dot(A, B)

# Print the result matrix C
print(C)
```

Numerical Example:
Suppose we have matrices `A` and `B` defined as shown above. The dimensions of matrices are `(2 x 3)` for `A` and `(3 x 2)` for `B`.

The result of matrix multiplication `C = np.dot(A, B)` will be:

```
C = [[58, 64],
     [139, 154]]
```

The element `C[0][0]` is computed as `(1 * 7) + (2 * 9) + (3 * 11) = 58`.
Similarly, the other elements of matrix `C` are computed using the dot product of corresponding rows and columns.

In this example, `np.dot()` automatically handles the matrix transpose, matching the dimensions of matrices `A` and `B` correctly for matrix multiplication.

I hope this clarifies the algorithm and provides an example of matrix multiplication using `np.dot()` in NumPy.

In [35]:
## MLP XOR solution experiment. 
import numpy as np
from sklearn.neural_network import MLPClassifier

# Define the XOR inputs and outputs
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

# Create and train an MLP classifier
mlp = MLPClassifier(hidden_layer_sizes=(2,), activation='relu', max_iter=10000)
mlp.fit(X, y)

# Test the trained MLP on XOR inputs
predictions = mlp.predict(X)
print(predictions)


[0 0 0 0]


In [19]:
print(X)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
