# Creating Vectors. 
 [ Reference ](https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.1-Scalars-Vectors-Matrices-and-Tensors/ )

In [1]:
import numpy as np
x = np.array([1,2,3,4])
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape # gives the no of rows and columns

# Leaning about Transpostion 
B = np.array([[1,2],[3,4],[5,6]])
print(B)
C = B.T
print(C)



[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [14]:
#BroadCasting 
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
B = np.array([[2], [4], [6]])
print(B)
C = A+B
print(C)


[[1 2]
 [3 4]
 [5 6]]
[[2]
 [4]
 [6]]
[[ 3  4]
 [ 7  8]
 [11 12]]


>shape[0] = rows 
>shape[1] = columns
[pthon_reference](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)


In [19]:
# Inverse of a matics 
np.eye(3)
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A
#multiplying an identitiy matrice
xid = np.eye(A.shape[0]).dot(A)
print(np.eye(A.shape[0]))
print(A)
#shape[0] = rows 
#shapep[1] = columns
print(A.shape[0])
print(xid)

# finding inverse 
A_inv = np.linalg.inv(A)
print(A_inv)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]
3
[[ 3.  0.  2.]
 [ 2.  0. -2.]
 [ 0.  1.  1.]]
[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]
